### ISSUE TITLE
Is validation correct??

### ISSUE THREAD

**Issue by smartinsightsfromdata** [andpol5/credit-classifier#1]
I reproduced your code getting similar results.

I have some doubts on the validation strategy.

The following line made me think that the code was selecting different sets of rows for train and validation:

```
for train_indices, val_indices in kf:
```

On the other hand, looking at the complete snippet:

```
for train_indices, val_indices in kf:
    # split the data into train and validation
    train_dataset = dataset[train_indices,:]
    val_dataset = dataset[train_indices,:]
```

Actually val_indices is not used in any other part of the code, and in reality looking at the above code it appears that we are using the same set for training and validation.

Am I missing something?

**Comment by andpol5** [comment]
@smartinsightsfromdata, thanks for finding the bug! Like you said just the matter of properly setting val_indices:
`val_dataset = dataset[val_indices,:]` 

I have addressed it in @4002fc3.
